In [21]:
#Task 1 A list of dictionaries

transactions = [
    {"id": 1, "product": "Laptop", "price": 1200, "quantity": 2, "region": "EU"},
    {"id": 2, "product": "Phone", "price": 800, "quantity": -1, "region": "US"},
    {"id": 3, "product": "Tablet", "price": 0, "quantity": 5, "region": "EU"},
    {"id": 4, "product": "Monitor", "price": 350, "quantity": 3, "region": "US"},
    {"id": 5, "product": "Laptop", "price": 1200, "quantity": 1, "region": "EU"},
    {"id": 6, "product": "Keyboard", "price": 75, "quantity": 10, "region": "APAC"},
]

# a) Filter invalid transactions
valid_transactions = []
for t in transactions: #"t for t in" assings t as an item in "transactions", which calls for the items only.
    if t["price"] > 0 and t["quantity"] >= 0:
        valid_transactions.append(t)


# b) Computing new field 
for t in valid_transactions:
    t["total"] = t["price"] * t["quantity"]
    

# c) Group by region and compute total revenue
revenue_by_region = {}

for t in valid_transactions:
    region = t["region"]
    if region not in revenue_by_region:
        revenue_by_region[region] = 0
    revenue_by_region[region] += t["total"]

# d) Find the region with the highest revenue
best_region = 0
highest = 0

for region in revenue_by_region:
    if highest is None or revenue_by_region[region] > highest:
        highest = revenue_by_region[region]
        best_region = region

print(f"The region with the highest total revenue is {best_region} with revenue of {highest}.")

The region with the highest total revenue is EU with revenue of 3600.


In [9]:
#Task 2 Creating a function

sales = [1200, 980, 1540, 870, 2010, 1650, 1300, 1100, 950, 1780, 2200, 1430, 1600, 1900]

def summarise_sales(sales_list):
    total = sum(sales_list)
    average = round(total / len(sales_list), 2)
    best_day = sales_list.index(max(sales_list)) + 1
    worst_day = sales_list.index(min(sales_list)) + 1
    above_average_count = sum(1 for sale in sales_list if sale > average)

    return {
    "total": total,
    "average": average,
    "best_day": best_day,
    "worst_day": worst_day,
    "above_average_count": above_average_count
    }

# Call the function with the list above and print the results
summary = summarise_sales(sales)
print(summary)

{'total': 20510, 'average': 1465.0, 'best_day': 11, 'worst_day': 4, 'above_average_count': 7}


In [23]:
#Task 3 Loops
students = [
    {"name": "Anna", "grade": 85, "attendance": 0.92},
    {"name": "Erik", "grade": 58, "attendance": 0.75},
    {"name": "Mia", "grade": 91, "attendance": 0.98},
    {"name": "Leo", "grade": 44, "attendance": 0.60},
    {"name": "Sara", "grade": 72, "attendance": 0.88},
    {"name": "Tom", "grade": 67, "attendance": 0.70},
    {"name": "Nina", "grade": 95, "attendance": 0.99},
    {"name": "Olli", "grade": 50, "attendance": 0.65},
]

# a) Create a list of those who passed
passing = []
for s in students:
    if s["grade"] >= 50:
        passing.append(s["name"])

print(passing)

# b) Loop through the students and print a status message for each. If the student's grade is 80 or above
for s in students:
    if s["grade"] >= 80:
        print(s["name"] + ": Excellent")
    elif s["grade"] >= 50:
        print(s["name"] + ": Pass")
    else:
        print(s["name"] + ": Fail")

# c) Count attendance rate of below 0.80
count = 0
for s in students:
    if s["attendance"] < 0.80:
        count += 1

print(count)

# d) Print the student with highest grade
top = students[0]
for s in students:
    if s["grade"] > top["grade"]:
        top = s

print(top["name"], top["grade"])

# e) Print student with highest grade
top_1 = max(students, key=lambda s: s["grade"])
print(top_1["name"], top_1["grade"])

['Anna', 'Erik', 'Mia', 'Sara', 'Tom', 'Nina', 'Olli']
Anna: Excellent
Erik: Pass
Mia: Excellent
Leo: Fail
Sara: Pass
Tom: Pass
Nina: Excellent
Olli: Pass
4
Nina 95
Nina 95


In [43]:
#Task 4 Class
class Portfolio:
    def __init__(self, owner):
        self.owner = owner
        self.holdings = {}  # ticker -> {shares, price_per_share}

# a) Adding assets
    def add_asset(self, ticker, shares, price_per_share):
        self.holdings[ticker] = {
            "shares": shares,
            "price_per_share": price_per_share
        }

# b) Total market value
    def total_value(self):
        total = 0
        for ticker in self.holdings:
            shares = self.holdings[ticker]["shares"]
            price = self.holdings[ticker]["price_per_share"]
            total += shares * price
        return total

# c) Return the ticker of the asset with the highest total value
    def most_valuable(self):
        best = 0
        highest = 0

        for ticker in self.holdings:
            value = self.holdings[ticker]["shares"] * self.holdings[ticker]["price_per_share"]
            if value > highest:
                highest = value
                best = ticker

        return best

# d) Return a readable summary of the portfolio, then print three instances
    def __str__(self):
        return f"{self.owner}'s portfolio has {len(self.holdings)} assets worth {self.total_value()}"

p = Portfolio("Batman")
p.add_asset("BAT", 10, 200)
p.add_asset("ROBN", 5, 250)
p.add_asset("JKR", 2, 3000)

print(p)
print(p.total_value())
print(p.most_valuable())

Batman's portfolio has 3 assets worth 9250
9250
JKR


In [55]:
#Task 5 Importing module
from datetime import datetime

orders = [
    ("2025-01-15", "Laptop"), ("2025-01-22", "Phone"),
    ("2025-02-03", "Laptop"), ("2025-02-14", "Tablet"),
    ("2025-03-01", "Phone"), ("2025-03-10", "Phone"),
    ("2025-03-22", "Laptop"), ("2025-04-05", "Monitor"),
]

dates = []

for order in orders:
    date_t = order[0]
    date_obj = datetime.strptime(date_t, "%Y-%m-%d").date()
    dates.append(date_obj)

earliest = min(dates)
latest = max(dates)

difference = latest - earliest
print(difference.days)

80


In [65]:
#Task 6 Array Operations and Broadcasting
import numpy as np

# Rows: years (2022, 2023, 2024), Columns: quarters (Q1, Q2, Q3, Q4)
revenue = np.array([
    [210, 230, 190, 250],
    [220, 260, 200, 270],
    [250, 290, 230, 310]])

# a) Compute and print the total annual revenue for each year
total = revenue.sum(axis=1)
print(total)

# b) Compute the mean quarterly revenue across all years
mean = revenue.mean(axis=0)
print(mean)

# c) Apply a growth adjustment to the 2024 row by multiplying it element-wise with the array [1.05, 1.03, 1.08, 1.02]. Print the adjusted values
growth = np.array([1.05, 1.03, 1.08, 1.02])
row_2024 = revenue[2]
adjusted = row_2024 * growth
print(adjusted)

# d) Use boolean indexing to find and print all quarterly revenue values that exceed 250
high_value = revenue[revenue > 250]
print(high_value)

[ 880  950 1080]
[226.66666667 260.         206.66666667 276.66666667]
[262.5 298.7 248.4 316.2]
[260 270 290 310]


In [77]:
#Task 7 Pandas
import pandas as pd

data = {
    "employee": ["Anna", "Erik", "Mia", "Leo", "Sara", "Tom"],
    "department": ["Finance", "Marketing", "Finance", "IT", "Marketing", "IT"],
    "salary": [4500, 4000, 4800, 5200, 3900, 5100],
    "years_exp": [5, 3, 7, 10, 2, 8],
    "performance_score": [4.2, 3.8, 4.5, 4.0, 3.5, 4.9]
}

df = pd.DataFrame(data)

# a) Add a new column salary_per_year_exp computed as salary / years_exp. Round to the nearest integer
df["salary_per_year_exp"] = df["salary"] / df["years_exp"]
df["salary_per_year_exp"] = df["salary_per_year_exp"].round()

# b) Sort the DataFrame by performance_score in descending order and print the top 3 employees
sort_df = df.sort_values("performance_score", ascending=False)
print(sort_df.head(3))

# c) Using .loc, select all employees in the Finance department with a performance score above 4.0
filtered = df.loc[(df["department"] == "Finance") & (df["performance_score"] > 4.0)]
print(filtered)

# d) Rename the column years_exp to experience_years using the .rename() method
df = df.rename(columns={"years_exp": "experience_years"})

# e) Using .iloc, select and print the salary and performance score columns for the first four employees
print(df.iloc[0:4][["salary", "performance_score"]])


  employee department  salary  years_exp  performance_score  \
5      Tom         IT    5100          8                4.9   
2      Mia    Finance    4800          7                4.5   
0     Anna    Finance    4500          5                4.2   

   salary_per_year_exp  
5                638.0  
2                686.0  
0                900.0  
  employee department  salary  years_exp  performance_score  \
0     Anna    Finance    4500          5                4.2   
2      Mia    Finance    4800          7                4.5   

   salary_per_year_exp  
0                900.0  
2                686.0  
   salary  performance_score
0    4500                4.2
1    4000                3.8
2    4800                4.5
3    5200                4.0


In [85]:
#Task 8 More pandas
import numpy as np
import pandas as pd

rng = np.random.default_rng(seed=123)
days = pd.date_range(start="2025-01-06", periods=28, freq="D")
visitors = rng.integers(200, 600, size=28)
conversion_rate = rng.uniform(0.02, 0.08, size=28).round(4)
avg_order_value = rng.normal(50, 10, size=28).round(2)

# a) Create a DataFrame with columns: date, visitors, conversion_rate, and avg_order_value. Set date as the index
df = pd.DataFrame({
    "date": days,
    "visitors": visitors,
    "conversion_rate": conversion_rate,
    "avg_order_value": avg_order_value})

df = df.set_index("date")

# b) Compute two new columns: conversions and daily_revenue
df["conversions"] = df["visitors"] * df["conversion_rate"]
df["conversions"] = df["conversions"].round()

df["daily_revenue"] = df["conversions"] * df["avg_order_value"]

print(df.head())

            visitors  conversion_rate  avg_order_value  conversions  \
date                                                                  
2025-01-06       206           0.0645            64.30         13.0   
2025-01-07       472           0.0578            48.44         27.0   
2025-01-08       437           0.0756            43.26         33.0   
2025-01-09       221           0.0339            43.61          7.0   
2025-01-10       563           0.0679            49.39         38.0   

            daily_revenue  
date                       
2025-01-06         835.90  
2025-01-07        1307.88  
2025-01-08        1427.58  
2025-01-09         305.27  
2025-01-10        1876.82  
